name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tarunb17
          password: Btharun6178@

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t tarunb17/hotstar-app:latest .
          docker push tarunb17/hotstar-app:latest

      # Step 4: Set up kubectl
      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # Step 5: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f K8S/
