name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tarunb17
          password: Btharun6178@

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t tarunb17/hotstar-app:latest .
          docker push tarunb17/hotstar-app:latest

      # Step 4: Set up kubectl
      - name: Set up kubectl
        run: |
          apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZGpMUGNKZkRXZ1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNE1ETXhPVFE0TURsYUZ3MHpOVEE0TURFeE9UVXpNRGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURMdWp6dUtybEpVQUhaWWp0SFZvTDdyQW5oT2haRGxZeTN6MGVZaG04SUFTVVozTDJmbllQOEF5UGkKK3dIWmo2aXd4MDY5azlXN3JkbDYwOXB1UUZvbHRUZFZXQ1pYWEh6ck1GOUFNQkZFcUdOeVV1NVFraElKK2tsSApiQnpvdFlHSGRPdGpMeFJPY3NRVTBCT2tZaUlkTVZVY0J0VmFRUnpxdURtaUtYbFB1ZEZFSkd3RUcrL1pyQ3BDCms3L2d3Z3c3ZlFtQXhJRDBJMThqVGZWU2NYVjAzOHMweG1XOXdDUVJvSHpPbTNZN0xseXZnWW9xSUFRWlM1Z1gKSUN5OEtMWWFNRTl4VGVaMHJwMFV3WVp4R0VoYXFZL0hUaUorM3JjS0hKNlBjZ3l4VjZnN1l3dm5wY2RLYUtvYwpKNWk0SHBhV1lmU3U4MEh3a1A3SkZCcGdXWnNaQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJURjlMeHV2NFZoWTR3OG9ac3YvV204TXl6NmRqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3YwZVUzQm1HUwpsVXZDeU5nNUNSUDdLNU5vT0FIWjk3dzhrMFovczhpcjB0SkVvZnZUUll5K3cyc2Jmb3F4Zk9PV1dUTWhZMHcyCnJXM1NHcU0xQXprV0l6blVWdDlyYllrOUNsMzlYNHoxS2VoVUZwOFJ0SFM1RlFJMExvK3Z1OHVZWFFFMkllOWgKTUlDS2lycDdLNFRQbXVqZ0N2amw0dkpwVG1Dbnd2akJEaW03VEh0RzVqNi85R1pFL0hGd2RIb1lVRjB0UmFOYwpteE4rN2kyRXg0SzhKSjhDVUIwSGlFWHp4NGtwRWlGZnVBMThMMUExakEyU3RBKzdJM3BFV2d0WkUya2dYa1FhCkh3Vk1kVDcwWkR6TDFBUldKWkJjWjhKaW8xcERkdzZOOFhnN1ZqYUpLZjR4aVNDay9ycElRTnRESFNrWEhRZDAKVjJnRmdKYW5taEdmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://172.31.92.81:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
-  name: kubernetes-admin
   user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJUm1WVXVoRldmbDB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNE1ETXhPVFE0TURsYUZ3MHlOakE0TURNeE9UVXpNVEphTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdUVKb2oKWXVDa0h0dFlnVEZFdGRMYzUzRE5OSWlzbmlrT3FrTlNOdnJiMEMyVFdwUzkzb09yclUyemRtVGphWTRPS01UTQp6OHNySmpsNFpab0toRWUrdGhFdXdXM0VzaG1jRDFaak1RYlFCdlZEaTZOS3JwdmFhWDZidzlNQ3lxU1lnaFBjCjE3NXFHV2lEbjZoNGFadmJiMEtIUzlMdHpyQTcyL1g0UWZsdzB4VFNyMWMyUzEzTzcwcjlaNVR4RWNwM1pLZm0KamNWYVZ6bDlzUWh4NWw2YXBxSFhCMU9pNUZYT3pEaTIwY0JyQlFxSjZvMloyMnhmcm01NnU4NG9vQ1NSNFdHZAo1enNLR3Uxc2ZzWk8zSkdaTVh1Uk9DaHZGSWVVWVV3dk1nRzhaZTBnZEdNMWI0Z0RNL21mQ1hCcExHcjNqT1N2CkU3WjVnOXJiT3dRTnJrNXJBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRk1YMHZHNi9oV0ZqakR5aApteS85YWJ3ekxQcDJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUEzWnFXRi9OUkNid2ozY2IwTysxdU0zN3JsClNlQXg0NFRLYWlpRWk2RWVZeHpyY1U3T2xkL0E4bXhZeE1GMW9iVmkwYjhaRkhSOHhxRjlsZ2U2Q2ZabmlJK0sKUTNFZ1lZaFpCcU1LenBoditFQjd2WVBxcHdrZExZNHhvSTVKQnpuRFVSaTRJNXNGdlUzRXRNSUFLR2tZajBuMgpmMzQ5REdiY1NVZ1hYTCsveE1ibEo1WmtZaXladGRiN2hTTHhPOWx2T0VtVGgrSlcwSkt5NmF3Ukk4OHRkSkZqCm4yaGUySDNhbVdUOTVuWUo5WnVzZmZYb3UvWDdzYkV1YnhaNkliVXJrYW5VUVNpSEgxazJoQTRuMlJDOU1hSlQKenRuMWx0RDhmcklNaFhFTDF5MEYyRUN2V3FNRUp5SlBZaEw0WFVRY3hSWXV4RVk3YkV1T3BiWEdjZkRSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcmhDYUkyTGdwQjdiV0lFeFJMWFMzT2R3elRTSXJKNHBEcXBEVWpiNjI5QXRrMXFVCnZkNkRxNjFOczNaazQybU9EaWpFek0vTEt5WTVlR1dhQ29SSHZyWVJMc0Z0eExJWm5BOVdZekVHMEFiMVE0dWoKU3E2YjJtbCttOFBUQXNxa21JSVQzTmUrYWhsb2c1K29lR21iMjI5Q2gwdlM3YzZ3Tzl2MStFSDVjTk1VMHE5WApOa3RkenU5Sy9XZVU4UkhLZDJTbjVvM0ZXbGM1ZmJFSWNlWmVtcWFoMXdkVG91UlZ6c3c0dHRIQWF3VUtpZXFOCm1kdHNYNjV1ZXJ2T0tLQWtrZUZobmVjN0NocnRiSDdHVHR5Um1URjdrVGdvYnhTSGxHRk1MeklCdkdYdElIUmoKTlcrSUF6UDVud2x3YVN4cTk0emtyeE8yZVlQYTJ6c0VEYTVPYXdJREFRQUJBb0lCQUNCNDFHaDVqN0xPVnRraAo4TkVDb24yM1oySEF4U1orc3VZYmVVZWpIaFZYdHNqZ2d4TVFxYnVqTHZXbHhwaHVIcVFoa3VVcWRwcHNIUmlLCnk3dmVoWXZjWjBRenJZaWVPUXpXQjZXbGhjSFZLbmdaV3JNWjg5VkJETzkrRHFWY3JHd1BDQ21RemVMNUxuZ3YKbHJ3djUzVitRZ2ovYWpBVytPV1IyVWNnOTZuR1NCM3JRVHhsUVkxWXpLMXlxWElUR2tPZC9EeHBBcnlZTXRvdgpsSVovTStjNmdXbldPSk90OTJxbFNvVTRuRmx2eWN1TTlxUzBNS3JXQTZLOGlXcC9JUWkrakJ5eEhKOG9DN0VNCk5IY2lhVmFoTE9MYnFkaVVnTmFreVd5SkZ5aHprbGNTaTlVT2YzL2pMMU1VR2ZDK00vaUFkWDdTaTR4TThLaG4KREF2UXlDRUNnWUVBMzU1TmZvT2oySW5Bc3djOVFCWndIVUt1MGwxWXJzSENnS29zOFh6WGhCc2wzWGRUbWpLdQo3bzRBWEVPM2dDNlBvcW1CRC81TVRUa2ZwNklZbE9URHZlSHFIRTB2TzA4WUlSbmowNVptaUpPK2l2ZExLendtCnJWNDlmVEdBWmJ1Q2dPWExCc0hsYmFnWUJHQ1VPZFBMNUMrdmhUT3VZODVVR1ptcktNNG5Sc2tDZ1lFQXgwVlEKWnF2bTExYWpROTJPRU9tY3hRK3ZXSnNRSzNXaW1GemQzSE8rbTJFQjNRaGs1c0NhV1NDZWhsWjU2TUNKOFNxYQpuQVNkQ2RBdzZ4aktnSVVOczRrOHorZko3K1VnVGVsK1pjWHRhMTd1Y3JjbElmWnpORG1mbyttcVZEdjJnS2J3CmZpdmhIUnljNnE5cUxZL2pWcHMydlpqTEZDQ1BiUTJqc251YTRaTUNnWUJoV05hL2hxc2pMd1MyYXlaYzZlZXcKdFVESnoxMDE1cCszeDExOVd5MnZFdXB1K08xcUtUcENHNHRJbnlvWklTdmlVZ3dmWEVMM016RDJsdmhBaVQ0MQpRVTNiT0RhaGlSTW1CZEZLWVNVTnU5T3RSMjV2eWVYRWYwd2hYaFZaTkVIaHZ5ZWRMM2VqUHhRRmc4M0RSdEp4CjZkaHRFa3lPb2xtMk0xRnhtQjA5RVFLQmdBSmNCNyt2ZVdSRFdsdUxYQXRIT052OGU0OEpCdi84dkpnaFFWOUMKMzViblp5WSsyek1BUk5PWlYwY3Y3dkdhbGdlTkFaZW5WbFN2YW1UZVBrZVhTN284ZmNQWWNzT3NhdDJCVGtYVwpPaUZ6Vms5MWE3TWpQK24yWkxXRUpzZ29qWnFvWDJDZkZHTkwyMi9MOCszbUxrTHdRNDJyS1h4cmhrYzhTaHZxCjZzS1JBb0dCQU5VdVJwVTNHb0pBc1VZeEVPS0RVc085OGc5aDY5RWNCQzA5OGtwamVoYXQyUWVLVytuZTM3K04KOTdHN1ZiTkVrckNXMkZlWXdDNmFYaGZqK085cW1oa2xwaHhBc3hBSjIxUFZidUtHWUJ6VXJTSHpSRkxieVd2ZApvMmkwbXZ6SGZXS3F4dVU4b3o1aUlJVGFsRzNtV3FVaHY3VDBFMGJiTS91YzNTVy9YdElPCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

 # Step 5: Deploy to Kubernetes
- name: Deploy to Kubernetes
  run: |
          kubectl apply -f K8S/
