name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tarunb17
          password: Btharun6178@

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t tarunb17/hotstar-app:latest .
          docker push tarunb17/hotstar-app:latest

      # Step 4: Deploy to Server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.83.130.129
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull tarunb17/hotstar-app:latest
            docker stop hotstar-app || true
            docker rm hotstar-app || true
            docker run -d --name hotstar-app -p 80:80 tarunb17/hotstar-app:latest
