name: Build and Deploy Hotstar App (Kubernetes with Tomcat)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Build WAR file
      - name: Build WAR
        run: mvn clean package

      # Step 4: Build Docker image with Tomcat
      - name: Build Docker Image
        run: docker build -t hotstar-app:latest .

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag hotstar-app:latest ${{ secrets.DOCKER_USERNAME }}/hotstar-app:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/hotstar-app:$IMAGE_TAG

      # Step 7: Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 8: Configure kubeconfig
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Step 9: Deploy using existing Kubernetes manifests
      - name: Deploy to Kubernetes
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          kubectl set image deployment/hotstar-app hotstar-app=${{ secrets.DOCKER_USERNAME }}/hotstar-app:$IMAGE_TAG || true
          kubectl apply -f k8s/

